# -*- coding: utf-8 -*-
"""emChedham00.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xecwaWzuMqn_9AZB_AOpBvzS0NaepPpp
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix

df = pd.read_csv("train_u6lujuX_CVtuZ9i.csv")

df = df.drop_duplicates()

df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)
df['Married'].fillna(df['Married'].mode()[0], inplace=True)
df['Dependents'].fillna(df['Dependents'].mode()[0], inplace=True)
df['Self_Employed'].fillna(df['Self_Employed'].mode()[0], inplace=True)

df['LoanAmount'].fillna(df['LoanAmount'].median(), inplace=True)
df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].median(), inplace=True)

df['Credit_History'].fillna(df['Credit_History'].mode()[0], inplace=True)

df['Dependents'] = df['Dependents'].replace('3+',3)
df['Dependents'] = df['Dependents'].astype(int)

Q1 = df['ApplicantIncome'].quantile(0.25)
Q3 = df['ApplicantIncome'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
df['ApplicantIncome'] = df['ApplicantIncome'].clip(lower, upper)

Q1 = df['CoapplicantIncome'].quantile(0.25)
Q3 = df['CoapplicantIncome'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
df['CoapplicantIncome'] = df['CoapplicantIncome'].clip(lower, upper)

Q1 = df['LoanAmount'].quantile(0.25)
Q3 = df['LoanAmount'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
df['LoanAmount'] = df['LoanAmount'].clip(lower, upper)

df['TotalIncome'] = df['ApplicantIncome'] + df['CoapplicantIncome']
df['LoanIncomeRatio'] = df['LoanAmount'] / df['TotalIncome']
df['EMIIncomeRatio'] = df['LoanAmount'] / df['Loan_Amount_Term']

df['Loan_Status'] = df['Loan_Status'].replace({'N':0,'Y':1})

df = pd.get_dummies(df, drop_first=True)

scaler = StandardScaler()
numerical_cols = ['ApplicantIncome','CoapplicantIncome','LoanAmount','TotalIncome']
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

X = df.drop(['Loan_Status'], axis=1)
y = df['Loan_Status']

from sklearn.feature_selection import mutual_info_classif
mi = mutual_info_classif(X,y)
mi_series = pd.Series(mi, index=X.columns)
print(mi_series.sort_values(ascending=False))


X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train,y_train)
pred_lr = lr.predict(X_test)

rf = RandomForestClassifier()
rf.fit(X_train,y_train)
pred_rf = rf.predict(X_test)

print("Accuracy:",accuracy_score(y_test,pred_rf))
print("Precision:",precision_score(y_test,pred_rf))
print("Recall:",recall_score(y_test,pred_rf))
print("F1 Score:",f1_score(y_test,pred_rf))

probs = rf.predict_proba(X_test)[:,1]
print("ROC-AUC:",roc_auc_score(y_test,probs))

cm = confusion_matrix(y_test,pred_rf)
sns.heatmap(cm,annot=True,fmt='d')
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

sample = X_test.iloc[0].values.reshape(1,-1)

prediction = rf.predict(sample)
probability = rf.predict_proba(sample)

print("Prediction:",prediction)
print("Approval Probability:",probability)

sns.countplot(x='Loan_Status',data=df)
plt.show()