# -*- coding: utf-8 -*-
"""emchedham02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZuF4Lza_nHrnPd-e6ppNohbBjmCYOze4
"""

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error
from copy import deepcopy
import warnings, time, os, sys
warnings.filterwarnings('ignore')

np.random.seed(42)

CSV_PATH = '/content/stock_details_5_years.csv'
TICKER   = 'MSFT'
OUT_DIR  = '/content'


def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-np.clip(x, -500, 500)))

def tanh(x):
    return np.tanh(np.clip(x, -500, 500))

def sigmoid_grad(s): return s * (1 - s)
def tanh_grad(t):    return 1 - t ** 2


def load_and_preprocess(path, ticker):
    df = pd.read_csv(path)
    if 'Company' in df.columns:
        df = df[df['Company'] == ticker].copy()
    if 'Date' not in df.columns:
        df = df.reset_index()
        df.rename(columns={df.columns[0]: 'Date'}, inplace=True)
    df['Date'] = pd.to_datetime(df['Date'])
    df = df.sort_values('Date').reset_index(drop=True)
    df = df.drop(columns=[c for c in ['Dividends', 'Stock Splits', 'Company'] if c in df.columns])
    df['Return']      = df['Close'].pct_change()
    df['MA_5']        = df['Close'].rolling(5).mean()
    df['MA_20']       = df['Close'].rolling(20).mean()
    df['Volatility']  = df['Return'].rolling(10).std()
    df['RSI']         = compute_rsi(df['Close'])
    df['Price_Range'] = (df['High'] - df['Low']) / df['Close']
    return df.dropna().reset_index(drop=True)


def compute_rsi(series, period=14):
    delta    = series.diff()
    avg_gain = delta.clip(lower=0).rolling(period).mean()
    avg_loss = (-delta.clip(upper=0)).rolling(period).mean()
    return 100 - (100 / (1 + avg_gain / (avg_loss + 1e-10)))


def create_sequences(df, feature_cols, target_col, window=10):
    scaler_X = MinMaxScaler()
    scaler_y = MinMaxScaler()
    X_scaled = scaler_X.fit_transform(df[feature_cols].values)
    y_scaled = scaler_y.fit_transform(df[target_col].values.reshape(-1, 1)).flatten()
    X, y, dates = [], [], []
    for i in range(window, len(X_scaled)):
        X.append(X_scaled[i - window:i])
        y.append(y_scaled[i])
        dates.append(df['Date'].iloc[i])
    return np.array(X), np.array(y), np.array(dates), scaler_y


def split(X, y, dates, train_r=0.70, val_r=0.15):
    t1, t2 = int(len(X) * train_r), int(len(X) * (train_r + val_r))
    return X[:t1], y[:t1], dates[:t1], X[t1:t2], y[t1:t2], dates[t1:t2], X[t2:], y[t2:], dates[t2:]


class LSTMCell:
    def __init__(self, input_dim, hidden_dim):
        self.input_dim = input_dim
        self.hidden_dim = hidden_dim
        scale = np.sqrt(2.0 / (input_dim + hidden_dim))
        self.W = np.random.randn(4 * hidden_dim, input_dim + hidden_dim) * scale
        self.b = np.zeros(4 * hidden_dim)
        self.mW = np.zeros_like(self.W); self.vW = np.zeros_like(self.W)
        self.mb = np.zeros_like(self.b); self.vb = np.zeros_like(self.b)

    def forward(self, x, h, c):
        xh = np.concatenate([x, h])
        z  = self.W @ xh + self.b
        H  = self.hidden_dim
        i_g = sigmoid(z[0:H]);   f_g = sigmoid(z[H:2*H])
        g_g = tanh(z[2*H:3*H]);  o_g = sigmoid(z[3*H:4*H])
        c_new = f_g * c + i_g * g_g
        h_new = o_g * tanh(c_new)
        return h_new, c_new, (x, h, c, i_g, f_g, g_g, o_g, c_new, h_new, xh)

    def backward(self, dh, dc, cache):
        x, h, c, i_g, f_g, g_g, o_g, c_new, h_new, xh = cache
        tan_c    = tanh(c_new)
        dc_total = dh * o_g * tanh_grad(tan_c) + dc
        dz = np.concatenate([
            dc_total * g_g  * sigmoid_grad(i_g),
            dc_total * c    * sigmoid_grad(f_g),
            dc_total * i_g  * tanh_grad(g_g),
            dh * tan_c      * sigmoid_grad(o_g),
        ])
        dxh = self.W.T @ dz
        return dxh[:self.input_dim], dxh[self.input_dim:], dc_total * f_g, np.outer(dz, xh), dz


class GRUCell:
    def __init__(self, input_dim, hidden_dim):
        self.input_dim = input_dim
        self.hidden_dim = hidden_dim
        scale = np.sqrt(2.0 / (input_dim + hidden_dim))
        self.Wz = np.random.randn(hidden_dim, input_dim + hidden_dim) * scale
        self.Wr = np.random.randn(hidden_dim, input_dim + hidden_dim) * scale
        self.Wh = np.random.randn(hidden_dim, input_dim + hidden_dim) * scale
        self.bz = np.zeros(hidden_dim)
        self.br = np.zeros(hidden_dim)
        self.bh = np.zeros(hidden_dim)
        for n in ['Wz','Wr','Wh','bz','br','bh']:
            setattr(self, 'm'+n, np.zeros_like(getattr(self, n)))
            setattr(self, 'v'+n, np.zeros_like(getattr(self, n)))

    def forward(self, x, h):
        xh  = np.concatenate([x, h])
        z   = sigmoid(self.Wz @ xh + self.bz)
        r   = sigmoid(self.Wr @ xh + self.br)
        xrh = np.concatenate([x, r * h])
        ht  = tanh(self.Wh @ xrh + self.bh)
        h_new = (1 - z) * h + z * ht
        return h_new, (x, h, z, r, ht, xh, xrh)

    def backward(self, dh, cache):
        x, h, z, r, ht, xh, xrh = cache
        dht   = dh * z * tanh_grad(ht)
        dz    = dh * (ht - h) * sigmoid_grad(z)
        dh_p  = dh * (1 - z)
        dxrh  = self.Wh.T @ dht
        dr    = dxrh[self.input_dim:] * h * sigmoid_grad(r)
        dh_p += dxrh[self.input_dim:] * r + (self.Wz.T @ dz)[self.input_dim:] + (self.Wr.T @ dr)[self.input_dim:]
        dx    = dxrh[:self.input_dim] + (self.Wz.T @ dz)[:self.input_dim] + (self.Wr.T @ dr)[:self.input_dim]
        return dx, dh_p, np.outer(dz,xh), np.outer(dr,xh), np.outer(dht,xrh), dz, dr, dht


class LSTMModel:
    def __init__(self, input_dim, hidden_dim=32, dropout=0.2, l2=1e-4):
        self.hidden_dim = hidden_dim
        self.dropout = dropout
        self.l2 = l2
        self.cell1 = LSTMCell(input_dim, hidden_dim)
        self.cell2 = LSTMCell(hidden_dim, hidden_dim)
        self.W_out = np.random.randn(1, hidden_dim) * 0.01
        self.b_out = np.zeros(1)
        self.mWo = np.zeros_like(self.W_out); self.vWo = np.zeros_like(self.W_out)
        self.mbo = np.zeros_like(self.b_out); self.vbo = np.zeros_like(self.b_out)
        self.t = 0

    def forward(self, X, training=True):
        h1 = c1 = h2 = c2 = np.zeros(self.hidden_dim)
        c1 = np.zeros(self.hidden_dim)
        c2 = np.zeros(self.hidden_dim)
        ca1, ca2 = [], []
        for x in X:
            h1, c1, cache1 = self.cell1.forward(x, h1, c1)
            if training and self.dropout > 0:
                h1 = h1 * (np.random.rand(*h1.shape) > self.dropout) / (1 - self.dropout)
            ca1.append(cache1)
            h2, c2, cache2 = self.cell2.forward(h1, h2, c2)
            if training and self.dropout > 0:
                h2 = h2 * (np.random.rand(*h2.shape) > self.dropout) / (1 - self.dropout)
            ca2.append(cache2)
        return (self.W_out @ h2 + self.b_out)[0], ca1, ca2, h2

    def backward(self, y_pred, y_true, ca1, ca2):
        dy   = 2 * (y_pred - y_true)
        h2   = ca2[-1][8]
        dh2  = (self.W_out * dy).flatten()
        dc2  = np.zeros(self.hidden_dim)
        dW1 = np.zeros_like(self.cell1.W); db1 = np.zeros_like(self.cell1.b)
        dW2 = np.zeros_like(self.cell2.W); db2 = np.zeros_like(self.cell2.b)
        for cache in reversed(ca2):
            _, dh2, dc2, dW2t, db2t = self.cell2.backward(dh2, dc2, cache)
            dW2 += dW2t; db2 += db2t
        dh1, dc1 = dh2, np.zeros(self.hidden_dim)
        for cache in reversed(ca1):
            _, dh1, dc1, dW1t, db1t = self.cell1.backward(dh1, dc1, cache)
            dW1 += dW1t; db1 += db1t
        dW1 += self.l2 * self.cell1.W
        dW2 += self.l2 * self.cell2.W
        return (y_pred - y_true)**2, {
            'dW1':dW1,'db1':db1,'dW2':dW2,'db2':db2,
            'dWo':dy * h2.reshape(1,-1),'dbo':np.array([dy])
        }

    def adam_update(self, grads, lr=0.001, b1=0.9, b2=0.999, eps=1e-8):
        self.t += 1
        def upd(p, g, m, v):
            m[:] = b1*m + (1-b1)*g
            v[:] = b2*v + (1-b2)*g**2
            p   -= lr * (m/(1-b1**self.t)) / (np.sqrt(v/(1-b2**self.t)) + eps)
        upd(self.cell1.W, grads['dW1'], self.cell1.mW, self.cell1.vW)
        upd(self.cell1.b, grads['db1'], self.cell1.mb, self.cell1.vb)
        upd(self.cell2.W, grads['dW2'], self.cell2.mW, self.cell2.vW)
        upd(self.cell2.b, grads['db2'], self.cell2.mb, self.cell2.vb)
        upd(self.W_out,   grads['dWo'], self.mWo,      self.vWo)
        upd(self.b_out,   grads['dbo'], self.mbo,      self.vbo)


class GRUModel:
    def __init__(self, input_dim, hidden_dim=32, dropout=0.2, l2=1e-4):
        self.hidden_dim = hidden_dim
        self.dropout = dropout
        self.l2 = l2
        self.cell1 = GRUCell(input_dim, hidden_dim)
        self.cell2 = GRUCell(hidden_dim, hidden_dim)
        self.W_out = np.random.randn(1, hidden_dim) * 0.01
        self.b_out = np.zeros(1)
        self.mWo = np.zeros_like(self.W_out); self.vWo = np.zeros_like(self.W_out)
        self.mbo = np.zeros_like(self.b_out); self.vbo = np.zeros_like(self.b_out)
        self.t = 0

    def forward(self, X, training=True):
        h1 = h2 = np.zeros(self.hidden_dim)
        ca1, ca2 = [], []
        for x in X:
            h1, cache1 = self.cell1.forward(x, h1)
            if training and self.dropout > 0:
                h1 = h1 * (np.random.rand(*h1.shape) > self.dropout) / (1 - self.dropout)
            ca1.append(cache1)
            h2, cache2 = self.cell2.forward(h1, h2)
            if training and self.dropout > 0:
                h2 = h2 * (np.random.rand(*h2.shape) > self.dropout) / (1 - self.dropout)
            ca2.append(cache2)
        return (self.W_out @ h2 + self.b_out)[0], ca1, ca2, h2

    def backward(self, y_pred, y_true, ca1, ca2):
        dy  = 2 * (y_pred - y_true)
        x2, h2p, z2, r2, ht2, xh2, xrh2 = ca2[-1]
        h2  = (1 - z2) * h2p + z2 * ht2
        dh2 = (self.W_out * dy).flatten()
        dWz1=np.zeros_like(self.cell1.Wz); dWr1=np.zeros_like(self.cell1.Wr); dWh1=np.zeros_like(self.cell1.Wh)
        dbz1=np.zeros_like(self.cell1.bz); dbr1=np.zeros_like(self.cell1.br); dbh1=np.zeros_like(self.cell1.bh)
        dWz2=np.zeros_like(self.cell2.Wz); dWr2=np.zeros_like(self.cell2.Wr); dWh2=np.zeros_like(self.cell2.Wh)
        dbz2=np.zeros_like(self.cell2.bz); dbr2=np.zeros_like(self.cell2.br); dbh2=np.zeros_like(self.cell2.bh)
        for cache in reversed(ca2):
            _, dh2, dWzt,dWrt,dWht,dbzt,dbrt,dbht = self.cell2.backward(dh2, cache)
            dWz2+=dWzt; dWr2+=dWrt; dWh2+=dWht; dbz2+=dbzt; dbr2+=dbrt; dbh2+=dbht
        dh1 = dh2
        for cache in reversed(ca1):
            _, dh1, dWzt,dWrt,dWht,dbzt,dbrt,dbht = self.cell1.backward(dh1, cache)
            dWz1+=dWzt; dWr1+=dWrt; dWh1+=dWht; dbz1+=dbzt; dbr1+=dbrt; dbh1+=dbht
        dWz1+=self.l2*self.cell1.Wz; dWr1+=self.l2*self.cell1.Wr; dWh1+=self.l2*self.cell1.Wh
        dWz2+=self.l2*self.cell2.Wz; dWr2+=self.l2*self.cell2.Wr; dWh2+=self.l2*self.cell2.Wh
        return (y_pred-y_true)**2, {
            'dWz1':dWz1,'dWr1':dWr1,'dWh1':dWh1,'dbz1':dbz1,'dbr1':dbr1,'dbh1':dbh1,
            'dWz2':dWz2,'dWr2':dWr2,'dWh2':dWh2,'dbz2':dbz2,'dbr2':dbr2,'dbh2':dbh2,
            'dWo':dy*h2.reshape(1,-1),'dbo':np.array([dy])
        }

    def adam_update(self, grads, lr=0.001, b1=0.9, b2=0.999, eps=1e-8):
        self.t += 1
        def upd(p, g, m, v):
            m[:] = b1*m + (1-b1)*g
            v[:] = b2*v + (1-b2)*g**2
            p   -= lr * (m/(1-b1**self.t)) / (np.sqrt(v/(1-b2**self.t)) + eps)
        c1, c2 = self.cell1, self.cell2
        upd(c1.Wz,grads['dWz1'],c1.mWz,c1.vWz); upd(c1.Wr,grads['dWr1'],c1.mWr,c1.vWr)
        upd(c1.Wh,grads['dWh1'],c1.mWh,c1.vWh); upd(c1.bz,grads['dbz1'],c1.mbz,c1.vbz)
        upd(c1.br,grads['dbr1'],c1.mbr,c1.vbr); upd(c1.bh,grads['dbh1'],c1.mbh,c1.vbh)
        upd(c2.Wz,grads['dWz2'],c2.mWz,c2.vWz); upd(c2.Wr,grads['dWr2'],c2.mWr,c2.vWr)
        upd(c2.Wh,grads['dWh2'],c2.mWh,c2.vWh); upd(c2.bz,grads['dbz2'],c2.mbz,c2.vbz)
        upd(c2.br,grads['dbr2'],c2.mbr,c2.vbr); upd(c2.bh,grads['dbh2'],c2.mbh,c2.vbh)
        upd(self.W_out,grads['dWo'],self.mWo,self.vWo)
        upd(self.b_out,grads['dbo'],self.mbo,self.vbo)


def train(model, X_tr, y_tr, X_val, y_val, epochs=120, lr=0.001, patience=20, name=''):
    best_val, best_model, patience_cnt = np.inf, None, 0
    tr_losses, val_losses, lr_cur = [], [], lr
    for epoch in range(1, epochs + 1):
        if epoch % 40 == 0:
            lr_cur *= 0.5
        for i in np.random.permutation(len(X_tr)):
            yp, c1, c2, _ = model.forward(X_tr[i])
            _, grads = model.backward(yp, y_tr[i], c1, c2)
            model.adam_update(grads, lr=lr_cur)
        tr_losses.append(sum((model.forward(X_tr[i], False)[0] - y_tr[i])**2 for i in range(len(X_tr))) / len(X_tr))
        vl = sum((model.forward(X_val[i], False)[0] - y_val[i])**2 for i in range(len(X_val))) / len(X_val)
        val_losses.append(vl)
        if vl < best_val:
            best_val, best_model, patience_cnt = vl, deepcopy(model), 0
        else:
            patience_cnt += 1
        if epoch % 20 == 0:
            print(f'  [{name}] Epoch {epoch:3d} | train={tr_losses[-1]:.5f} | val={vl:.5f}')
        if patience_cnt >= patience:
            print(f'  [{name}] Early stop at epoch {epoch}')
            break
    return best_model, tr_losses, val_losses


def predict(model, X):
    return np.array([model.forward(X[i], False)[0] for i in range(len(X))])


def evaluate(y_true, y_pred, scaler):
    yt = scaler.inverse_transform(y_true.reshape(-1,1)).flatten()
    yp = scaler.inverse_transform(y_pred.reshape(-1,1)).flatten()
    return {
        'RMSE': np.sqrt(mean_squared_error(yt, yp)),
        'MAE':  mean_absolute_error(yt, yp),
        'MAPE': np.mean(np.abs((yt - yp) / (yt + 1e-8))) * 100,
        'DirAcc': np.mean(np.sign(np.diff(yt)) == np.sign(np.diff(yp))) * 100,
        'yt': yt, 'yp': yp
    }


def main():
    df = load_and_preprocess(CSV_PATH, TICKER)
    print(f'{TICKER}: {len(df)} rows | {df["Date"].min().date()} → {df["Date"].max().date()}')

    FEATURES = ['Close','Return','MA_5','MA_20','Volatility','RSI','Price_Range','Volume']
    X, y, dates, scaler_y = create_sequences(df, FEATURES, 'Close', window=10)
    X_tr,y_tr,d_tr, X_val,y_val,d_val, X_te,y_te,d_te = split(X, y, dates)
    print(f'Train={len(X_tr)} | Val={len(X_val)} | Test={len(X_te)}')

    input_dim = X.shape[2]

    print('\nTraining LSTM...')
    lstm,  lstm_tl,  lstm_vl  = train(LSTMModel(input_dim), X_tr, y_tr, X_val, y_val, name='LSTM')

    print('\nTraining GRU...')
    gru,   gru_tl,   gru_vl   = train(GRUModel(input_dim),  X_tr, y_tr, X_val, y_val, name='GRU')

    print('\nAblation: LSTM no dropout...')
    lstm_nd, nd_tl, nd_vl = train(LSTMModel(input_dim, dropout=0.0), X_tr, y_tr, X_val, y_val, name='NoDrop')

    print('\nAblation: LSTM no L2...')
    lstm_nl, nl_tl, nl_vl = train(LSTMModel(input_dim, l2=0.0), X_tr, y_tr, X_val, y_val, name='NoL2')

    m = {
        'LSTM':    evaluate(y_te, predict(lstm,    X_te), scaler_y),
        'GRU':     evaluate(y_te, predict(gru,     X_te), scaler_y),
        'NoDrop':  evaluate(y_te, predict(lstm_nd, X_te), scaler_y),
        'NoL2':    evaluate(y_te, predict(lstm_nl, X_te), scaler_y),
    }

    print('\n{:<10} {:>8} {:>8} {:>8} {:>8}'.format('Model','RMSE','MAE','MAPE%','Dir%'))
    print('-' * 46)
    for name, v in m.items():
        print(f'{name:<10} {v["RMSE"]:>8.2f} {v["MAE"]:>8.2f} {v["MAPE"]:>8.2f} {v["DirAcc"]:>8.1f}')

    # ── Plots ──────────────────────────────────────────────────────

    # 1. Training curves
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    for ax, tl, vl, label in [
        (axes[0], lstm_tl, lstm_vl, 'LSTM'),
        (axes[1], gru_tl,  gru_vl,  'GRU'),
    ]:
        ax.plot(tl, label='Train')
        ax.plot(vl, label='Val', linestyle='--')
        ax.set_title(f'{label} Loss')
        ax.set_xlabel('Epoch'); ax.set_ylabel('MSE')
        ax.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(OUT_DIR, 'fig_training.png'), dpi=120, bbox_inches='tight')
    plt.show()

    # 2. Predictions vs actuals
    fig, axes = plt.subplots(2, 2, figsize=(14, 8))
    for ax, key, color in zip(axes.flatten(),
                               ['LSTM','GRU','NoDrop','NoL2'],
                               ['tab:blue','tab:green','tab:red','tab:orange']):
        ax.plot(d_te, m[key]['yt'], label='Actual', color='black', lw=1)
        ax.plot(d_te, m[key]['yp'], label='Predicted', color=color, lw=1, linestyle='--')
        ax.set_title(f'{key}  RMSE={m[key]["RMSE"]:.2f}')
        ax.legend(fontsize=8)
        ax.tick_params(labelsize=7)
    plt.suptitle('Predictions vs Actual')
    plt.tight_layout()
    plt.savefig(os.path.join(OUT_DIR, 'fig_predictions.png'), dpi=120, bbox_inches='tight')
    plt.show()

    # 3. Ablation curves
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    for ax, tl2, vl2, label in [
        (axes[0], nd_tl, nd_vl, 'No Dropout vs LSTM'),
        (axes[1], nl_tl, nl_vl, 'No L2 vs LSTM'),
    ]:
        ax.plot(lstm_tl, label='LSTM train');      ax.plot(lstm_vl, '--', label='LSTM val')
        ax.plot(tl2,     label=f'{label} train');  ax.plot(vl2,     '--', label=f'{label} val')
        ax.set_title(label); ax.set_xlabel('Epoch'); ax.set_ylabel('MSE')
        ax.legend(fontsize=8)
    plt.tight_layout()
    plt.savefig(os.path.join(OUT_DIR, 'fig_ablation.png'), dpi=120, bbox_inches='tight')
    plt.show()

    # 4. Error analysis
    fig, axes = plt.subplots(1, 3, figsize=(14, 4))
    res_lstm = m['LSTM']['yp'] - m['LSTM']['yt']
    res_gru  = m['GRU']['yp']  - m['GRU']['yt']
    axes[0].hist(res_lstm, bins=25, alpha=0.7, label='LSTM')
    axes[0].hist(res_gru,  bins=25, alpha=0.7, label='GRU')
    axes[0].axvline(0, color='black', lw=1); axes[0].set_title('Residuals'); axes[0].legend()
    axes[1].plot(d_te, res_lstm, label='LSTM', lw=1)
    axes[1].plot(d_te, res_gru,  label='GRU',  lw=1)
    axes[1].axhline(0, color='black', lw=1); axes[1].set_title('Residuals over Time'); axes[1].legend()
    names = list(m.keys())
    x = np.arange(len(names))
    axes[2].bar(x - 0.2, [m[n]['RMSE'] for n in names], 0.4, label='RMSE')
    axes[2].bar(x + 0.2, [m[n]['MAE']  for n in names], 0.4, label='MAE')
    axes[2].set_xticks(x); axes[2].set_xticklabels(names); axes[2].legend()
    axes[2].set_title('RMSE & MAE')
    plt.tight_layout()
    plt.savefig(os.path.join(OUT_DIR, 'fig_errors.png'), dpi=120, bbox_inches='tight')
    plt.show()

    return m

if __name__ == '__main__':
    main()